import Head from "next/head";
import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "antd/dist/antd.css";
import NavBar from "../comps/NavBar";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>E-Learning Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/book.ico" />
      </Head>

      <NavBar />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
